### ISSUE TITLE
Broken template 2

### ISSUE THREAD

**Issue by Subfortytwo** [enigmampc/SecretJS-Templates#25]
Looks like the protocol has changed, can you help, please?
thx

```
$ node 2_creating_account/create_account.js 
Error: Unexpected response data format
    at RestClient.authAccounts (/home/username/scrt/SecretJS-Templates/node_modules/secretjs/build/restclient.js:107:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by levackt** [comment]
For this and most other examples you just have to change the secretjs version to "0.17.3" in package.json

**Comment by Subfortytwo** [comment]
OMG thx  you <3
